class MyError(Exception):
    """putilの基底エラー"""
    


    
   
