from pyutil.ziputil.error.ZiputilError import ZiputilError


class ZipFileExistsError(ZiputilError,FileExistsError):...


